### PR TITLE
Gracefully handle possible non-array return value of imap_getmailboxes

### PR DESCRIPTION
**Pull request by Slamdunk**
Reference: https://github.com/ddeboer/imap/issues/134

@robertodormepoco please can you checkout my branch [imap_getmailboxes_non_array](https://github.com/Slamdunk/imap/tree/imap_getmailboxes_non_array) and report here the full exception error message, so I can better document what happens?

### CODE REVIEW

**Comment by robertodormepoco** [comment]
Done

```
In Connection.php line 207:

  [Ddeboer\Imap\Exception\ImapGetmailboxesException]
  imap_getmailboxes failed
  imap_alerts (0):
  imap_errors (0):
```

but, as I've stated before, in the C code the result is nullable, i think it would be better to check diffs between errors before and after the call, because the result value is not a valuable indicator of failure.
Though i also don't like exceptions bubbling up from private methods, the init logic for the mailbox list should be explicit and handled outside, but that's the current design so that's not the point right now.

```
object(Ddeboer\Imap\ImapResource)#175 (2) {
  ["resource":"Ddeboer\Imap\ImapResource":private]=>
  resource(170) of type (imap)
  ["mailbox":"Ddeboer\Imap\ImapResource":private]=>
  NULL
}
string(80) "{gmail-imap.l.google.com:993/imap/notls/ssl/user="**email-address**"}"

Warning: Invalid argument supplied for foreach() in /var/app/vendor/ddeboer/imap/src/Connection.php on line 211
```

This was the warning for the invalid variable passed as countable to foreach, with some variable dump just ($this->resource, $this->server), and it looks fine.

**Comment by Slamdunk** [comment]
> I've stated before, in the C code the result is nullable

I've read carefully your reply but honestly I have almost-zero knowledge of C and php-src

> I think it would be better to check diffs between errors before and after the call, because the result value is not a valuable indicator of failure.

I don't get what you mean with this

>  Though i also don't like exceptions bubbling up from private methods, the init logic for the mailbox list should be explicit and handled outside

Without the current design, how would you get both lazy-loading and crappy imap extension error handling?

> This was the warning for the invalid variable passed as countable to foreach, with some variable dump just ($this->resource, $this->server), and it looks fine.

What do you mean by "it looks fine"?


If you have any suggestion on how to improve this, please PR against my branch or this library.
This stuff is a pain in the ass because it's hard to test without going to the real world.

Last but not least, fa sempre piacere trovare un connazionale preparato :wink:

**Comment by Slamdunk** [comment]
So, AFAICT there is nothing we can improve in this imap-extension flaw, and this PR is everything we can get to handle the issue.

Nevertheless I would like at least to:

1. set up a dedicated test environment
1. reproduce the issue
1. document it

Could you describe here:

1. the email provider that generates the issue
1. the entire folder structure that allegedly is responsible for the issue

So I can reproduce it in a dedicated real email account?

**Comment by Slamdunk** [comment]
We should investigate `imap_ping` impact on performance. Take for example https://github.com/ddeboer/imap/issues/326 checking everything at every step is unfeasable.

**Pull request merged**
