### PR TITLE
Add `subscribeMailbox` to `Connection`

### PR DESCRIPTION
**Pull request by Ruud68**
So just ran into the same 'issue' as here: #448 and thought why not create a PR for it: first PR on this repo so hope it is okay or otherwise would love some feedback on what to change / improve.

I have added subscribeMailbox as a separate method and not as part of the createMailbox method as I am not sure if all IMAP servers support subscribing.
Having it as a separate function gives more flexibility.

### CODE REVIEW

**Comment by Slamdunk** [comment]
Tests are indeed missing. Once you added them, please run:

```console
make start-imap-server
make
```

**Comment by Ruud68** [comment]
Hi @Slamdunk thanks for following up.
just for your information:
I installed docker to be able to run the test but didn't succeed.
so what I ran into:
in docker, php-cs-fixer, phpstan, php-unit not installed, error reporting that composer.json was missing from /usr/srv/app
I was able to install these into the docker image by changing the Makefile.
Ran into issues where the $(pdw) used was missing (had to replace that in the Makefile, including the calling of the e.g. $(PHP_BIN) vendor/bin/php-cs-fixer fix --verbose  which I corrected to $(PHP_BIN) php vendor/bin/php-cs-fixer fix --verbose (note the php executable).

Next I ran into the docker image not having the php-imap extension installed. managed to install it but finally gave up because although installed it was reporting that it was not enabled....

So after two hours of fiddling around, I can at least tell you that if the test code I added was succesfull I wouldn't trust it being actual successfull :))

In short: I gave up.

I have updated the PR with the testcode I produced: hope it helps and also hope my feedback helps to get this docker thing working correct on noob setups.

This is as much I as I can do to contribute

**Comment by Slamdunk** [comment]
> in docker, php-cs-fixer, phpstan, php-unit not installed

Not sure why this happens for you, but `make start-imap-server ; make` is all you need to build locally this project.
`make start-imap-server` starts the imap server, and than `make` install all the dependencies, the dev tools and runs the build, you don't have to install anything nor edit anything.

This is the output of the two commands so you can compare them to yours:

<details>
    <summary><code>make start-imap-server</code></summary>

	$ make start-imap-server
	docker pull thecodingmachine/php:8.3-v4-cli
	8.3-v4-cli: Pulling from thecodingmachine/php
	3823320faa42: Pull complete
	bd90f255e40c: Pull complete
	2bbf99b06c74: Pull complete
	8c7b30bb6c64: Pull complete
	702964ada6e3: Pull complete
	4d201d03dfcc: Pull complete
	5c180eac3b41: Pull complete
	6258887767a6: Pull complete
	13b2c6da815a: Pull complete
	c0656c2373ed: Pull complete
	8a15e2325caf: Pull complete
	292a3c09d904: Pull complete
	b6ee722ee12a: Pull complete
	397262b24e31: Pull complete
	77a870417792: Pull complete
	bf269fece6f4: Pull complete
	4f4fb700ef54: Pull complete
	dc9eae37d61b: Pull complete
	536c80c24848: Pull complete
	63f2cbaa08a5: Pull complete
	1f53db483127: Pull complete
	00e94814d632: Pull complete
	7f06562082f0: Pull complete
	778071773838: Pull complete
	1529b4a5c0e6: Pull complete
	e3d3fb237700: Pull complete
	18f5902225ba: Pull complete
	8beeb03b208c: Pull complete
	0e9e60561081: Pull complete
	fd7a5e9b236b: Pull complete
	6f170a3d472d: Pull complete
	c68f0b89201c: Pull complete
	843393d54243: Pull complete
	cc1db02b4aaa: Pull complete
	Digest: sha256:f0ea43cea4f09e7e81ac5bf0ddecface65338e011087f18060b528bc42f9b9f3
	Status: Downloaded newer image for thecodingmachine/php:8.3-v4-cli
	docker.io/thecodingmachine/php:8.3-v4-cli
	docker pull antespi/docker-imap-devel:latest
	latest: Pulling from antespi/docker-imap-devel
	c62795f78da9: Pull complete
	d4fceeeb758e: Pull complete
	5c9125a401ae: Pull complete
	0062f774e994: Pull complete
	6b33fd031fac: Pull complete
	703ece94a020: Pull complete
	88621f0ce677: Pull complete
	86c475219b80: Pull complete
	f6da479d4316: Pull complete
	388100df4979: Pull complete
	c35b93dc5d58: Pull complete
	Digest: sha256:5e248858824590426eafe64e0803da842077cca1cb2a56cf63333b3d5a9af3db
	Status: Downloaded newer image for antespi/docker-imap-devel:latest
	docker.io/antespi/docker-imap-devel:latest
	docker network create ddeboer_imap_network
	21814e8ae6c30e7631e794c961690b7f46b107ba36ea96a7c2c7598baeeb1bb7
	docker run \
			--name=ddeboer_imap_server \
			--network=ddeboer_imap_network \
			--detach \
			--rm \
			--expose 993 \
			--publish 10993:993 \
			--env MAILNAME=test.test \
			--env MAIL_ADDRESS=test@test.test \
			--env MAIL_PASS=p4ssword \
			antespi/docker-imap-devel:latest
	c56fb5ca3aa59bb3eb23f81f264ed9e514c96b00edcf5180c3450b8981b4dd0d
	./wait-for-it localhost:10993
	wait-for-it: waiting 15 seconds for localhost:10993
	wait-for-it: localhost:10993 is available after 0 seconds
</details>

<details>
    <summary><code>make</code></summary>

	$ make
	docker run -it --rm --network=ddeboer_imap_network --env IMAP_SERVER_NAME=ddeboer_imap_server --env IMAP_SERVER_PORT=993 --env IMAP_USERNAME=test@test.test --env IMAP_PASSWORD=p4ssword --env PHP_EXTENSION_IMAP=1 --env PHP_EXTENSION_PCOV=1 -v "/home/tessarotto/repos/imap":"/home/tessarotto/repos/imap" -w "/home/tessarotto/repos/imap" thecodingmachine/php:8.3-v4-cli composer update
	Loading composer repositories with package information
	Updating dependencies
	Lock file operations: 72 installs, 0 updates, 0 removals
	  - Locking clue/ndjson-react (v1.3.0)
	  - Locking composer/pcre (3.3.1)
	  - Locking composer/semver (3.4.3)
	  - Locking composer/xdebug-handler (3.0.5)
	  - Locking evenement/evenement (v3.0.2)
	  - Locking fidry/cpu-core-counter (1.2.0)
	  - Locking friendsofphp/php-cs-fixer (v3.64.0)
	  - Locking laminas/laminas-loader (2.10.0)
	  - Locking laminas/laminas-mail (2.25.1)
	  - Locking laminas/laminas-mime (2.12.0)
	  - Locking laminas/laminas-servicemanager (3.22.1)
	  - Locking laminas/laminas-stdlib (3.19.0)
	  - Locking laminas/laminas-validator (2.64.1)
	  - Locking myclabs/deep-copy (1.12.0)
	  - Locking nikic/php-parser (v5.3.1)
	  - Locking phar-io/manifest (2.0.4)
	  - Locking phar-io/version (3.2.1)
	  - Locking phpstan/phpstan (1.12.6)
	  - Locking phpstan/phpstan-phpunit (1.4.0)
	  - Locking phpstan/phpstan-strict-rules (1.6.1)
	  - Locking phpunit/php-code-coverage (11.0.7)
	  - Locking phpunit/php-file-iterator (5.1.0)
	  - Locking phpunit/php-invoker (5.0.1)
	  - Locking phpunit/php-text-template (4.0.1)
	  - Locking phpunit/php-timer (7.0.1)
	  - Locking phpunit/phpunit (11.4.1)
	  - Locking psr/container (1.1.2)
	  - Locking psr/event-dispatcher (1.0.0)
	  - Locking psr/http-message (2.0)
	  - Locking psr/log (3.0.2)
	  - Locking react/cache (v1.2.0)
	  - Locking react/child-process (v0.6.5)
	  - Locking react/dns (v1.13.0)
	  - Locking react/event-loop (v1.5.0)
	  - Locking react/promise (v3.2.0)
	  - Locking react/socket (v1.16.0)
	  - Locking react/stream (v1.4.0)
	  - Locking sebastian/cli-parser (3.0.2)
	  - Locking sebastian/code-unit (3.0.1)
	  - Locking sebastian/code-unit-reverse-lookup (4.0.1)
	  - Locking sebastian/comparator (6.1.0)
	  - Locking sebastian/complexity (4.0.1)
	  - Locking sebastian/diff (6.0.2)
	  - Locking sebastian/environment (7.2.0)
	  - Locking sebastian/exporter (6.1.3)
	  - Locking sebastian/global-state (7.0.2)
	  - Locking sebastian/lines-of-code (3.0.1)
	  - Locking sebastian/object-enumerator (6.0.1)
	  - Locking sebastian/object-reflector (4.0.1)
	  - Locking sebastian/recursion-context (6.0.2)
	  - Locking sebastian/type (5.1.0)
	  - Locking sebastian/version (5.0.2)
	  - Locking symfony/console (v7.1.5)
	  - Locking symfony/deprecation-contracts (v3.5.0)
	  - Locking symfony/event-dispatcher (v7.1.1)
	  - Locking symfony/event-dispatcher-contracts (v3.5.0)
	  - Locking symfony/filesystem (v7.1.5)
	  - Locking symfony/finder (v7.1.4)
	  - Locking symfony/options-resolver (v7.1.1)
	  - Locking symfony/polyfill-ctype (v1.31.0)
	  - Locking symfony/polyfill-intl-grapheme (v1.31.0)
	  - Locking symfony/polyfill-intl-idn (v1.31.0)
	  - Locking symfony/polyfill-intl-normalizer (v1.31.0)
	  - Locking symfony/polyfill-mbstring (v1.31.0)
	  - Locking symfony/polyfill-php80 (v1.31.0)
	  - Locking symfony/polyfill-php81 (v1.31.0)
	  - Locking symfony/process (v7.1.5)
	  - Locking symfony/service-contracts (v3.5.0)
	  - Locking symfony/stopwatch (v7.1.1)
	  - Locking symfony/string (v7.1.5)
	  - Locking theseer/tokenizer (1.2.3)
	  - Locking webmozart/assert (1.11.0)
	Writing lock file
	Installing dependencies from lock file (including require-dev)
	Package operations: 72 installs, 0 updates, 0 removals
	  - Downloading composer/pcre (3.3.1)
	  - Downloading symfony/deprecation-contracts (v3.5.0)
	  - Downloading psr/container (1.1.2)
	  - Downloading symfony/service-contracts (v3.5.0)
	  - Downloading symfony/stopwatch (v7.1.1)
	  - Downloading symfony/process (v7.1.5)
	  - Downloading symfony/polyfill-php81 (v1.31.0)
	  - Downloading symfony/polyfill-php80 (v1.31.0)
	  - Downloading symfony/polyfill-mbstring (v1.31.0)
	  - Downloading symfony/options-resolver (v7.1.1)
	  - Downloading symfony/finder (v7.1.4)
	  - Downloading symfony/polyfill-ctype (v1.31.0)
	  - Downloading symfony/filesystem (v7.1.5)
	  - Downloading psr/event-dispatcher (1.0.0)
	  - Downloading symfony/event-dispatcher-contracts (v3.5.0)
	  - Downloading symfony/event-dispatcher (v7.1.1)
	  - Downloading symfony/polyfill-intl-normalizer (v1.31.0)
	  - Downloading symfony/polyfill-intl-grapheme (v1.31.0)
	  - Downloading symfony/string (v7.1.5)
	  - Downloading symfony/console (v7.1.5)
	  - Downloading sebastian/diff (6.0.2)
	  - Downloading react/event-loop (v1.5.0)
	  - Downloading evenement/evenement (v3.0.2)
	  - Downloading react/stream (v1.4.0)
	  - Downloading react/promise (v3.2.0)
	  - Downloading react/cache (v1.2.0)
	  - Downloading react/dns (v1.13.0)
	  - Downloading react/socket (v1.16.0)
	  - Downloading react/child-process (v0.6.5)
	  - Downloading fidry/cpu-core-counter (1.2.0)
	  - Downloading psr/log (3.0.2)
	  - Downloading composer/xdebug-handler (3.0.5)
	  - Downloading composer/semver (3.4.3)
	  - Downloading clue/ndjson-react (v1.3.0)
	  - Downloading friendsofphp/php-cs-fixer (v3.64.0)
	  - Downloading webmozart/assert (1.11.0)
	  - Downloading symfony/polyfill-intl-idn (v1.31.0)
	  - Downloading psr/http-message (2.0)
	  - Downloading laminas/laminas-stdlib (3.19.0)
	  - Downloading laminas/laminas-servicemanager (3.22.1)
	  - Downloading laminas/laminas-validator (2.64.1)
	  - Downloading laminas/laminas-mime (2.12.0)
	  - Downloading laminas/laminas-loader (2.10.0)
	  - Downloading laminas/laminas-mail (2.25.1)
	  - Downloading phpstan/phpstan (1.12.6)
	  - Downloading phpstan/phpstan-phpunit (1.4.0)
	  - Downloading phpstan/phpstan-strict-rules (1.6.1)
	  - Downloading sebastian/version (5.0.2)
	  - Downloading sebastian/type (5.1.0)
	  - Downloading sebastian/recursion-context (6.0.2)
	  - Downloading sebastian/object-reflector (4.0.1)
	  - Downloading sebastian/object-enumerator (6.0.1)
	  - Downloading sebastian/global-state (7.0.2)
	  - Downloading sebastian/exporter (6.1.3)
	  - Downloading sebastian/environment (7.2.0)
	  - Downloading sebastian/comparator (6.1.0)
	  - Downloading sebastian/code-unit (3.0.1)
	  - Downloading sebastian/cli-parser (3.0.2)
	  - Downloading phpunit/php-timer (7.0.1)
	  - Downloading phpunit/php-text-template (4.0.1)
	  - Downloading phpunit/php-invoker (5.0.1)
	  - Downloading phpunit/php-file-iterator (5.1.0)
	  - Downloading theseer/tokenizer (1.2.3)
	  - Downloading nikic/php-parser (v5.3.1)
	  - Downloading sebastian/lines-of-code (3.0.1)
	  - Downloading sebastian/complexity (4.0.1)
	  - Downloading sebastian/code-unit-reverse-lookup (4.0.1)
	  - Downloading phpunit/php-code-coverage (11.0.7)
	  - Downloading phar-io/version (3.2.1)
	  - Downloading phar-io/manifest (2.0.4)
	  - Downloading myclabs/deep-copy (1.12.0)
	  - Downloading phpunit/phpunit (11.4.1)
	  - Installing composer/pcre (3.3.1): Extracting archive
	  - Installing symfony/deprecation-contracts (v3.5.0): Extracting archive
	  - Installing psr/container (1.1.2): Extracting archive
	  - Installing symfony/service-contracts (v3.5.0): Extracting archive
	  - Installing symfony/stopwatch (v7.1.1): Extracting archive
	  - Installing symfony/process (v7.1.5): Extracting archive
	  - Installing symfony/polyfill-php81 (v1.31.0): Extracting archive
	  - Installing symfony/polyfill-php80 (v1.31.0): Extracting archive
	  - Installing symfony/polyfill-mbstring (v1.31.0): Extracting archive
	  - Installing symfony/options-resolver (v7.1.1): Extracting archive
	  - Installing symfony/finder (v7.1.4): Extracting archive
	  - Installing symfony/polyfill-ctype (v1.31.0): Extracting archive
	  - Installing symfony/filesystem (v7.1.5): Extracting archive
	  - Installing psr/event-dispatcher (1.0.0): Extracting archive
	  - Installing symfony/event-dispatcher-contracts (v3.5.0): Extracting archive
	  - Installing symfony/event-dispatcher (v7.1.1): Extracting archive
	  - Installing symfony/polyfill-intl-normalizer (v1.31.0): Extracting archive
	  - Installing symfony/polyfill-intl-grapheme (v1.31.0): Extracting archive
	  - Installing symfony/string (v7.1.5): Extracting archive
	  - Installing symfony/console (v7.1.5): Extracting archive
	  - Installing sebastian/diff (6.0.2): Extracting archive
	  - Installing react/event-loop (v1.5.0): Extracting archive
	  - Installing evenement/evenement (v3.0.2): Extracting archive
	  - Installing react/stream (v1.4.0): Extracting archive
	  - Installing react/promise (v3.2.0): Extracting archive
	  - Installing react/cache (v1.2.0): Extracting archive
	  - Installing react/dns (v1.13.0): Extracting archive
	  - Installing react/socket (v1.16.0): Extracting archive
	  - Installing react/child-process (v0.6.5): Extracting archive
	  - Installing fidry/cpu-core-counter (1.2.0): Extracting archive
	  - Installing psr/log (3.0.2): Extracting archive
	  - Installing composer/xdebug-handler (3.0.5): Extracting archive
	  - Installing composer/semver (3.4.3): Extracting archive
	  - Installing clue/ndjson-react (v1.3.0): Extracting archive
	  - Installing friendsofphp/php-cs-fixer (v3.64.0): Extracting archive
	  - Installing webmozart/assert (1.11.0): Extracting archive
	  - Installing symfony/polyfill-intl-idn (v1.31.0): Extracting archive
	  - Installing psr/http-message (2.0): Extracting archive
	  - Installing laminas/laminas-stdlib (3.19.0): Extracting archive
	  - Installing laminas/laminas-servicemanager (3.22.1): Extracting archive
	  - Installing laminas/laminas-validator (2.64.1): Extracting archive
	  - Installing laminas/laminas-mime (2.12.0): Extracting archive
	  - Installing laminas/laminas-loader (2.10.0): Extracting archive
	  - Installing laminas/laminas-mail (2.25.1): Extracting archive
	  - Installing phpstan/phpstan (1.12.6): Extracting archive
	  - Installing phpstan/phpstan-phpunit (1.4.0): Extracting archive
	  - Installing phpstan/phpstan-strict-rules (1.6.1): Extracting archive
	  - Installing sebastian/version (5.0.2): Extracting archive
	  - Installing sebastian/type (5.1.0): Extracting archive
	  - Installing sebastian/recursion-context (6.0.2): Extracting archive
	  - Installing sebastian/object-reflector (4.0.1): Extracting archive
	  - Installing sebastian/object-enumerator (6.0.1): Extracting archive
	  - Installing sebastian/global-state (7.0.2): Extracting archive
	  - Installing sebastian/exporter (6.1.3): Extracting archive
	  - Installing sebastian/environment (7.2.0): Extracting archive
	  - Installing sebastian/comparator (6.1.0): Extracting archive
	  - Installing sebastian/code-unit (3.0.1): Extracting archive
	  - Installing sebastian/cli-parser (3.0.2): Extracting archive
	  - Installing phpunit/php-timer (7.0.1): Extracting archive
	  - Installing phpunit/php-text-template (4.0.1): Extracting archive
	  - Installing phpunit/php-invoker (5.0.1): Extracting archive
	  - Installing phpunit/php-file-iterator (5.1.0): Extracting archive
	  - Installing theseer/tokenizer (1.2.3): Extracting archive
	  - Installing nikic/php-parser (v5.3.1): Extracting archive
	  - Installing sebastian/lines-of-code (3.0.1): Extracting archive
	  - Installing sebastian/complexity (4.0.1): Extracting archive
	  - Installing sebastian/code-unit-reverse-lookup (4.0.1): Extracting archive
	  - Installing phpunit/php-code-coverage (11.0.7): Extracting archive
	  - Installing phar-io/version (3.2.1): Extracting archive
	  - Installing phar-io/manifest (2.0.4): Extracting archive
	  - Installing myclabs/deep-copy (1.12.0): Extracting archive
	  - Installing phpunit/phpunit (11.4.1): Extracting archive
	11 package suggestions were added by new dependencies, use `composer suggest` to see details.
	Package laminas/laminas-mail is abandoned, you should avoid using it. Use symfony/mailer instead.
	Generating autoload files
	62 packages you are using are looking for funding.
	Use the `composer fund` command to find out more!
	No security vulnerability advisories found.
	docker run -it --rm --network=ddeboer_imap_network --env IMAP_SERVER_NAME=ddeboer_imap_server --env IMAP_SERVER_PORT=993 --env IMAP_USERNAME=test@test.test --env IMAP_PASSWORD=p4ssword --env PHP_EXTENSION_IMAP=1 --env PHP_EXTENSION_PCOV=1 -v "/home/tessarotto/repos/imap":"/home/tessarotto/repos/imap" -w "/home/tessarotto/repos/imap" thecodingmachine/php:8.3-v4-cli composer bump
	Warning: Bumping dependency constraints is not recommended for libraries as it will narrow down your dependencies and may cause problems for your users.
	If your package is not a library, you can explicitly specify the "type" by using "composer config type project".
	Alternatively you can use --dev-only to only bump dependencies within "require-dev".
	./composer.json has been updated (2 changes).
	touch vendor
	docker run -it --rm --network=ddeboer_imap_network --env IMAP_SERVER_NAME=ddeboer_imap_server --env IMAP_SERVER_PORT=993 --env IMAP_USERNAME=test@test.test --env IMAP_PASSWORD=p4ssword --env PHP_EXTENSION_IMAP=1 --env PHP_EXTENSION_PCOV=1 -v "/home/tessarotto/repos/imap":"/home/tessarotto/repos/imap" -w "/home/tessarotto/repos/imap" thecodingmachine/php:8.3-v4-cli vendor/bin/php-cs-fixer fix --verbose
	PHP CS Fixer 3.64.0 Space Sets by Fabien Potencier, Dariusz Ruminski and contributors.
	PHP runtime: 8.3.12
	Running analysis on 1 core sequentially.
	You can enable parallel runner and speed up the analysis! Please see usage docs for more information.
	Loaded config default from "/home/tessarotto/repos/imap/.php-cs-fixer.php".
	 93/93 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


	Fixed 0 of 93 files in 10.852 seconds, 26.00 MB memory used
	docker run -it --rm --network=ddeboer_imap_network --env IMAP_SERVER_NAME=ddeboer_imap_server --env IMAP_SERVER_PORT=993 --env IMAP_USERNAME=test@test.test --env IMAP_PASSWORD=p4ssword --env PHP_EXTENSION_IMAP=1 --env PHP_EXTENSION_PCOV=1 -v "/home/tessarotto/repos/imap":"/home/tessarotto/repos/imap" -w "/home/tessarotto/repos/imap" thecodingmachine/php:8.3-v4-cli vendor/bin/phpstan analyse
	Note: Using configuration file /home/tessarotto/repos/imap/phpstan.neon.
	 93/93 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%



	 [OK] No errors


	docker run -it --rm --network=ddeboer_imap_network --env IMAP_SERVER_NAME=ddeboer_imap_server --env IMAP_SERVER_PORT=993 --env IMAP_USERNAME=test@test.test --env IMAP_PASSWORD=p4ssword --env PHP_EXTENSION_IMAP=1 --env PHP_EXTENSION_PCOV=1 -v "/home/tessarotto/repos/imap":"/home/tessarotto/repos/imap" -w "/home/tessarotto/repos/imap" thecodingmachine/php:8.3-v4-cli php \
			-d zend.assertions=1 \
			vendor/bin/phpunit \

	PHPUnit 11.4.1 by Sebastian Bergmann and contributors.

	Runtime:       PHP 8.3.12 with PCOV 1.0.11
	Configuration: /home/tessarotto/repos/imap/phpunit.xml.dist

	...S...................I.I.....................................  63 / 169 ( 37%)
	............................................................... 126 / 169 ( 74%)
	...I.......................................                     169 / 169 (100%)

	Time: 00:52.390, Memory: 20.00 MB

	OK, but there were issues!
	Tests: 169, Assertions: 970, Skipped: 1, Incomplete: 3.

	Generating code coverage report in HTML format ... done [00:00.126]


	Code Coverage Report Summary:
	  Classes: 82.22% (37/45)
	  Methods: 89.50% (162/181)
	  Lines:   93.68% (712/760)

	Done.
</details>

**Comment by Ruud68** [comment]
just to follow up:
sudo make start-imap-server works correct and starts the docker instance,
image

then the sudo make gives the following error:
image

As said, I am not versed enough (nor have the time available) to learn the ins-and-outs of docker: so this is not going to work for me.

Probably best to test the PR yourself. Or not accept it > not to keen on running my own fork, but that would also be an option for me.

Anyway hope this helps!

**Comment by Slamdunk** [comment]
I see that `PWD` is not present in you environment variables, could you please try to re-run the `make` command after substituting `"$(PWD)"` with `"$(shell pwd)"`?

**Comment by Ruud68** [comment]
Hi that was the first change I made yesterday , first of many changes needed after that: see https://github.com/ddeboer/imap/pull/581#issuecomment-2410786825 where I already mention having replaced that environment variable.

Anyway, I think the 'issue' was in the codestyle for the {} on the exception I created. Fixed that so lets see if it will run correct now

**Pull request merged**
