### PR TITLE
Added support for embedded message

### PR DESCRIPTION
**Pull request by artemevsin**
Added support for embedded messages. Useful while working with multiple emails resended in one email.

### CODE REVIEW

**Comment by marcusorjames** [comment]
Hi, was this branch ever perused, one of my clients is interested in having embedded attachment support.

**Comment by artemevsin** [comment]
hi, we use this fork in our project, which is used by 3 our clients so we process about 3000 mails/month and it just works without any problem. But I remember that there was some issues like bad encoding or some bugs related to unexpected structure of mail. I'll be happy if you will try this and I'll glad to help you if you will encounter any issues to improve this feature

**Comment by marcusorjames** [comment]
Great thank you. I will have a go and let you know if I have any problems :)

**Comment by Slamdunk** [comment]
Merged in https://github.com/ddeboer/imap/pull/216 thank you very much!

**Pull request closed without merging**
