### PR TITLE
Update Mailbox.php

### PR DESCRIPTION
**Pull request by maisoui**
relative to #469

### CODE REVIEW

**Comment by Slamdunk** [comment]
Hi, really appreciate you first-time contribution.

I need to ask you to also redact a test to prove the outgoing results match the expectation

**Comment by maisoui** [comment]
I'm not sure to understand what you want but here is a dummy sample :

`$mailbox = $connection->getMailbox($mailboxName);

$thread = $mailbox->getThread();

//retrieve message numbers from thread
$messageNumbers = [];
foreach($thread as $key => $messageNumber) {
	$tree = explode('.', $key);
	if($tree[1] === 'branch' || $tree[1] === 'next') {
		continue;
	}

	if($messageNumber !== 0 && !in_array($messageNumber, $messageNumbers)) {
		$messageNumbers[] = $messageNumber;
	}
}

//get messages according to message numbers present in thread
$mailbox->getMessageSequence(implode(',', $messageNumbers));`

Regards

**Comment by Slamdunk** [comment]
Have you ever practiced Test-Driven Development?

For every piece of code in `src/`, there should be another piece of code in `tests/` that demonstrate the effectiveness of the `src/` code.

This ensure that future breaking changes don't go unnoticed, and you can prove to the maintainer of the library that the change does what is expected to do.

**Comment by maisoui** [comment]
I'm sorry, I don't understand what more I can do. All necessary code already exists in `tests/`. The only difference is that the integer returns by `getThread` will be a message number (UID) instead of a sequence number (i.e. index), and is now compatible with `getMessageSequence` and your use of `FT_UID` argument.
It's really a minor bug-fix, I don't understand why it's so complicated... My goal was only to help you.

**Comment by Slamdunk** [comment]
> The only difference is that the integer returns by `getThread` will be a message number (UID) instead of a sequence number (i.e. index)

Saying the code does this and proving it are quite different things.

> I don't understand why it's so complicated

Maintaining a library for everyone guaranteeing everything works as expected is complicated, and needs a curated test process. 

> My goal was only to help you.

I appreciate your help, and I'm trying to help you to understand how proving everyone that you're code works is much more reliable than just saying it works

**Pull request closed without merging**
